[package]
name = "swegov-opendata"
version = "0.2.1"
edition = { workspace = true }
authors = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
deserx = { workspace = true }
miette = { workspace = true }
quick-xml = { workspace = true, features = ["serde-types"] }
serde = { workspace = true, features = ["derive"] }
serde-aux = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
quick-xml = { workspace = true, features = ["serialize"] }
similar-asserts = { workspace = true }
